import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,nextBattle,living,attack,checkOutcome,validGame} from '../src/game.js';

test('victory carries only survivors, promotes veterans and adds recruits',()=>{const first=createGame();first.result='victory';first.units.find(u=>u.id==='goblin-1').hp=0;first.freshGoblins=2;first.charmPoints=1;const second=nextBattle(first);assert.equal(second.scenarioId,'tribal-merger');assert.equal(living(second,'player').filter(u=>u.type==='veteran').length,9);assert.equal(living(second,'player').filter(u=>u.type==='goblin').length,2);assert.ok(living(second,'player').filter(u=>u.type==='veteran').every(u=>u.hp===10));assert.equal(second.charmPoints,1);assert.ok(second.introPending);assert.ok(validGame(second));assert.equal(nextBattle(second),null);});
test('rival tribe roster has two shamans, a charmable champion and four charmable goblins',()=>{const g=createGame(19,'tribal-merger');assert.equal(living(g,'enemy').length,7);assert.equal(g.units.filter(u=>u.type==='shaman').length,2);assert.equal(g.units.find(u=>u.type==='champion').hp,36);assert.equal(g.units.filter(u=>u.team==='enemy'&&u.charmable).length,5);});
test('shamans attack at three tiles, spending mana, and cannot attack beyond range',()=>{const g=createGame(19,'tribal-merger'),shaman=g.units.find(u=>u.type==='shaman'),mother=g.units[0];g.turn='enemy';mother.x=10;mother.y=10;shaman.x=13;shaman.y=10;assert.equal(attack(g,mother.id,shaman.id),true);assert.equal(shaman.mp,14);assert.ok(mother.hp>=20&&mother.hp<=22);shaman.acted=false;shaman.x=14;assert.equal(attack(g,mother.id,shaman.id),false);});
test('only broodmother and charmed champion remaining wins immediately on charm',()=>{const g=createGame(19,'tribal-merger'),mother=g.units[0],champion=g.units.find(u=>u.type==='champion');for(const u of g.units)if(u!==mother&&u!==champion)u.hp=0;champion.x=mother.x+1;champion.y=mother.y;assert.equal(checkOutcome(g),null);assert.equal(attack(g,champion.id),true);assert.equal(g.result,'victory-charm');});
test('eliminating the rival tribe wins and broodmother death loses',()=>{const g=createGame(19,'tribal-merger');for(const u of living(g,'enemy'))u.hp=0;assert.equal(checkOutcome(g),'victory');const lost=createGame(19,'tribal-merger');lost.units[0].hp=0;assert.equal(checkOutcome(lost),'defeat');});
