import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,reachable,moveUnit,selectUnit,attack,castPower,endTurn,finishEnemyTurn,exchangeCharmPoint,validGame,living} from '../src/game.js';

test('Greenwood roster and charm traits come from scenario definitions',()=>{const g=createGame();assert.equal(g.terrain.length,25);assert.equal(living(g,'player').length,11);assert.equal(living(g,'enemy').length,4);assert.equal(g.units.filter(u=>u.team==='enemy'&&u.charmable).length,2);assert.equal(g.units.filter(u=>u.team==='enemy'&&!u.charmable).length,2);assert.equal(g.units[0].hp,25);assert.equal(g.units[0].mp,25);assert.ok(g.units.filter(u=>u.type==='goblin').every(u=>u.hp===6));assert.ok(validGame(g));});
test('selected units spend movement and cannot enter trees or occupied cells',()=>{const g=createGame();selectUnit(g,'goblin-1');const u=g.units.find(a=>a.id==='goblin-1');g.terrain[u.y][u.x+1]='tree';assert.equal(moveUnit(g,u.x+1,u.y),false);assert.equal(moveUnit(g,5,12),false);assert.equal(moveUnit(g,3,11),true);assert.equal(u.movesLeft,3);assert.equal(reachable(g,u).get('3,10'),1);});
test('club deals one to two damage and each goblin attacks once per round',()=>{const g=createGame();const goblin=g.units.find(u=>u.id==='goblin-1'),human=g.units.find(u=>u.id==='human-1');human.x=goblin.x+1;human.y=goblin.y;const before=human.hp;selectUnit(g,goblin.id);assert.equal(attack(g,human.id),true);assert.ok(before-human.hp>=1&&before-human.hp<=2);assert.equal(attack(g,human.id),false);});
test('broodmother powers replace each other and charm skips one human turn',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.id==='human-1');assert.equal(castPower(g,'enhance'),true);assert.equal(mother.mp,20);assert.equal(g.activePower.kind,'enhance');mother.acted=false;assert.equal(castPower(g,'weaken'),true);assert.equal(g.activePower.kind,'weaken');mother.acted=false;human.x=mother.x+1;human.y=mother.y;assert.equal(attack(g,human.id),true);assert.equal(g.activePower.kind,'charm');const position=[human.x,human.y];endTurn(g);finishEnemyTurn(g);assert.deepEqual([human.x,human.y],position);assert.equal(g.activePower,null);});
test('humans prefer goblins and endings resolve',()=>{const g=createGame(),mother=g.units[0],goblin=g.units.find(u=>u.id==='goblin-1'),human=g.units.find(u=>u.id==='human-1');for(const u of g.units)if(u.type==='goblin'&&u!==goblin)u.hp=0;for(const u of g.units)if(u.type==='human'&&u!==human)u.hp=0;mother.x=12;mother.y=12;goblin.x=14;goblin.y=12;goblin.hp=1;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]=g.terrain[12][14]='plain';endTurn(g);finishEnemyTurn(g);assert.equal(mother.hp,25);assert.equal(goblin.hp,0);assert.equal(g.result,'last-mother');});
test('defeating the last human wins',()=>{const g=createGame(),goblin=g.units.find(u=>u.type==='goblin'),human=g.units.find(u=>u.type==='human');for(const u of g.units)if(u.type==='human'&&u!==human)u.hp=0;human.hp=1;human.x=goblin.x+1;human.y=goblin.y;selectUnit(g,goblin.id);assert.equal(attack(g,human.id),true);assert.equal(g.result,'victory');});
test('losing the broodmother to humans leads to capture',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.type==='human');for(const u of g.units)if(u.type==='goblin')u.hp=0;mother.hp=1;mother.x=12;mother.y=12;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]='plain';endTurn(g);finishEnemyTurn(g);assert.equal(g.result,'captured');});
test('a human attacks the broodmother when she is the only adjacent target',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.type==='human');mother.x=12;mother.y=12;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]='plain';endTurn(g);finishEnemyTurn(g);assert.ok(mother.hp<25);});
test('only charmable enemies award points and humans award two only once',()=>{const g=createGame(),mother=g.units[0],blue=g.units.find(u=>u.charmable),resolute=g.units.find(u=>u.team==='enemy'&&!u.charmable);resolute.x=mother.x+1;resolute.y=mother.y;assert.equal(attack(g,resolute.id),false);assert.equal(mother.acted,false);assert.equal(g.charmPoints,0);blue.x=mother.x+1;blue.y=mother.y;resolute.x=20;resolute.y=20;assert.equal(attack(g,blue.id),true);assert.equal(g.charmPoints,2);mother.acted=false;assert.equal(attack(g,blue.id),true);assert.equal(g.charmPoints,2);});
test('a charmed human attacks an adjacent resolute human who retaliates next round',()=>{const g=createGame(),mother=g.units[0],blue=g.units.find(u=>u.charmable),resolute=g.units.find(u=>u.team==='enemy'&&!u.charmable);for(const u of g.units)if(u.team==='enemy'&&u!==blue&&u!==resolute)u.hp=0;mother.x=5;mother.y=12;blue.x=6;blue.y=12;resolute.x=7;resolute.y=12;for(let x=5;x<=7;x++)g.terrain[12][x]='plain';assert.equal(attack(g,blue.id),true);const resoluteHp=resolute.hp;endTurn(g);finishEnemyTurn(g);assert.ok(resolute.hp<resoluteHp);assert.equal(resolute.retaliateAgainst,blue.id);assert.equal(resolute.retaliateRound,2);const blueHp=blue.hp;endTurn(g);finishEnemyTurn(g);assert.ok(blue.hp<blueHp);assert.equal(resolute.retaliateAgainst,null);});
test('charm points can be exchanged for fresh goblins after battle',()=>{const g=createGame();g.charmPoints=2;g.charmedIds=['human-1','human-4'];g.result='victory';assert.equal(exchangeCharmPoint(g),true);assert.equal(g.charmPoints,1);assert.equal(g.freshGoblins,1);assert.equal(exchangeCharmPoint(g),true);assert.equal(exchangeCharmPoint(g),false);assert.equal(g.freshGoblins,2);});
