import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,reachable,moveUnit,selectUnit,attack,castPower,endTurn,finishEnemyTurn,validGame,living} from '../src/game.js';

test('Greenwood roster and stats come from scenario definitions',()=>{const g=createGame();assert.equal(g.terrain.length,25);assert.equal(living(g,'player').length,11);assert.equal(living(g,'enemy').length,3);assert.equal(g.units[0].hp,25);assert.equal(g.units[0].mp,25);assert.ok(g.units.filter(u=>u.type==='goblin').every(u=>u.hp===6));assert.ok(validGame(g));});
test('selected units spend movement and cannot enter trees or occupied cells',()=>{const g=createGame();selectUnit(g,'goblin-1');const u=g.units.find(a=>a.id==='goblin-1');g.terrain[u.y][u.x+1]='tree';assert.equal(moveUnit(g,u.x+1,u.y),false);assert.equal(moveUnit(g,5,12),false);assert.equal(moveUnit(g,3,11),true);assert.equal(u.movesLeft,3);assert.equal(reachable(g,u).get('3,10'),1);});
test('club deals one to two damage and each goblin attacks once per round',()=>{const g=createGame();const goblin=g.units.find(u=>u.id==='goblin-1'),human=g.units.find(u=>u.id==='human-1');human.x=goblin.x+1;human.y=goblin.y;const before=human.hp;selectUnit(g,goblin.id);assert.equal(attack(g,human.id),true);assert.ok(before-human.hp>=1&&before-human.hp<=2);assert.equal(attack(g,human.id),false);});
test('broodmother powers replace each other and charm skips one human turn',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.id==='human-1');assert.equal(castPower(g,'enhance'),true);assert.equal(mother.mp,20);assert.equal(g.activePower.kind,'enhance');mother.acted=false;assert.equal(castPower(g,'weaken'),true);assert.equal(g.activePower.kind,'weaken');mother.acted=false;human.x=mother.x+1;human.y=mother.y;assert.equal(attack(g,human.id),true);assert.equal(g.activePower.kind,'charm');const position=[human.x,human.y];endTurn(g);finishEnemyTurn(g);assert.deepEqual([human.x,human.y],position);assert.equal(g.activePower,null);});
test('humans prefer goblins and endings resolve',()=>{const g=createGame(),mother=g.units[0],goblin=g.units.find(u=>u.id==='goblin-1'),human=g.units.find(u=>u.id==='human-1');for(const u of g.units)if(u.type==='goblin'&&u!==goblin)u.hp=0;for(const u of g.units)if(u.type==='human'&&u!==human)u.hp=0;mother.x=12;mother.y=12;goblin.x=14;goblin.y=12;goblin.hp=1;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]=g.terrain[12][14]='plain';endTurn(g);finishEnemyTurn(g);assert.equal(mother.hp,25);assert.equal(goblin.hp,0);assert.equal(g.result,'last-mother');});
test('defeating the last human wins',()=>{const g=createGame(),goblin=g.units.find(u=>u.type==='goblin'),human=g.units.find(u=>u.type==='human');for(const u of g.units)if(u.type==='human'&&u!==human)u.hp=0;human.hp=1;human.x=goblin.x+1;human.y=goblin.y;selectUnit(g,goblin.id);assert.equal(attack(g,human.id),true);assert.equal(g.result,'victory');});
test('losing the broodmother ends the battle',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.type==='human');for(const u of g.units)if(u.type==='goblin')u.hp=0;mother.hp=1;mother.x=12;mother.y=12;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]='plain';endTurn(g);finishEnemyTurn(g);assert.equal(g.result,'defeat');});
test('a human attacks the broodmother when she is the only adjacent target',()=>{const g=createGame(),mother=g.units[0],human=g.units.find(u=>u.type==='human');mother.x=12;mother.y=12;human.x=13;human.y=12;g.terrain[12][12]=g.terrain[12][13]='plain';endTurn(g);finishEnemyTurn(g);assert.ok(mother.hp<25);});
