import {scenarios,unitTypes} from './scenarios.js';
export const TILE=64;
export const DIRECTIONS=[[1,0],[-1,0],[0,1],[0,-1]];
const key=(x,y)=>`${x},${y}`;
const distance=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const alive=u=>u.hp>0;
export const living=(game,team)=>game.units.filter(u=>alive(u)&&(!team||u.team===team));
export const selected=game=>game.units.find(u=>u.id===game.selectedId&&alive(u));
export const scenario=game=>scenarios[game.scenarioId];
export function createGame(seed=19,scenarioId='greenwood'){
  const map=scenarios[scenarioId];if(!map)throw Error('Unknown scenario');
  let value=seed>>>0;const random=()=>((value=(1664525*value+1013904223)>>>0)/4294967296);
  const terrain=Array.from({length:map.height},(_,y)=>Array.from({length:map.width},(_,x)=>map.clearings.some(c=>Math.abs(x-c.x)<=c.radius&&Math.abs(y-c.y)<=c.radius)?'plain':random()<map.treeChance?'tree':'plain'));
  const units=map.units.map(spec=>{const type=unitTypes[spec.type];terrain[spec.y][spec.x]='plain';return {...spec,charmable:spec.charmable??false,team:spec.team??type.team,hp:type.maxHp,mp:type.maxMp,movesLeft:type.move,acted:false,charmedRound:0,stunnedRound:0,invisible:false,retaliateAgainst:null,retaliateRound:0}});
  return {version:3,charmRewardVersion:2,scenarioId,seed,terrain,units,selectedId:units[0].id,turn:'player',round:1,activePower:null,result:null,introPending:true,charmPoints:0,charmedIds:[],freshGoblins:0,moveHistory:[],herbsCollected:[],completedMissions:[],log:['The battle begins.']};
}
export function reachable(game,unit=selected(game),limit=unit?.movesLeft??0){
  const result=new Map();if(!unit||!alive(unit))return result;
  const map=scenario(game),queue=[[unit.x,unit.y]];result.set(key(unit.x,unit.y),0);
  for(let i=0;i<queue.length;i++){const [x,y]=queue[i],cost=result.get(key(x,y));if(cost>=limit)continue;
    for(const [dx,dy] of DIRECTIONS){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx<0||ny<0||nx>=map.width||ny>=map.height||game.terrain[ny][nx]==='tree'||result.has(k)||living(game).some(u=>u.id!==unit.id&&u.x===nx&&u.y===ny))continue;result.set(k,cost+1);queue.push([nx,ny]);}}
  return result;
}
export function selectUnit(game,id){const unit=game.units.find(u=>u.id===id&&alive(u)&&u.controllable!==false);if(!unit)return false;game.selectedId=id;return true;}
export function moveUnit(game,x,y,id=game.selectedId){const unit=game.units.find(u=>u.id===id&&alive(u));if(!unit||unit.controllable===false||game.result||game.turn!==unit.team||unit.charmedRound===game.round||unit.stunnedRound===game.round)return false;const cost=reachable(game,unit).get(key(x,y));if(!cost)return false;if(unit.team==='player')(game.moveHistory??=[]).push({unitId:unit.id,fromX:unit.x,fromY:unit.y,cost});unit.x=x;unit.y=y;unit.movesLeft-=cost;if(unit.team==='player'&&scenario(game).objective.kind==='collect'){const herb=scenario(game).herbs?.find(h=>h.x===x&&h.y===y),mark=key(x,y);if(herb&&!game.herbsCollected.includes(mark)){game.herbsCollected.push(mark);game.moveHistory=[];log(game,`Collected silverleaf (${game.herbsCollected.length}/${scenario(game).objective.required}).`);outcome(game);}}return true;}
export function undoMove(game){const history=game.moveHistory;if(game.turn!=='player'||game.result||!history?.length)return false;const last=history.at(-1),unit=game.units.find(u=>u.id===last.unitId&&alive(u));if(!unit||living(game).some(u=>u.id!==unit.id&&u.x===last.fromX&&u.y===last.fromY))return false;unit.x=last.fromX;unit.y=last.fromY;unit.movesLeft+=last.cost;game.selectedId=unit.id;history.pop();return true;}
function roll(game,min,max){let v=(game.seed=(1664525*game.seed+1013904223)>>>0);return min+v%(max-min+1);}
function log(game,message){game.log.unshift(message);game.log=game.log.slice(0,8);}
export function checkOutcome(game){if(game.result)return game.result;const players=living(game,'player'),enemies=living(game,'enemy'),objective=scenario(game).objective;if(objective.kind==='hub')return null;const protectedTypes=objective.protectTypes??[objective.protectType].filter(Boolean);if(protectedTypes.some(type=>!players.some(u=>u.type===type)))game.result=objective.captureOnLoss?'captured':'defeat';else if(objective.kind==='collect')game.result=(game.herbsCollected?.length??0)>=objective.required?'victory':null;else if(!enemies.length)game.result='victory';else if(objective.charmedLastType&&players.length===1&&enemies.length===1&&enemies[0].type===objective.charmedLastType&&enemies[0].charmedRound===game.round)game.result='victory-charm';else if(objective.specialLastType&&players.length===1&&players[0].type===objective.specialLastType)game.result='last-mother';return game.result;}
function outcome(game){const previous=game.result;checkOutcome(game);if(game.result&&!previous)log(game,game.result==='victory'?'Mission complete!':game.result==='victory-charm'?'The champion accepts the broodmother. The tribes are united.':game.result==='captured'?'The humans have captured the broodmother.':game.result==='defeat'?'The mission has failed.':'Only the broodmother remains.');}
function hit(game,attacker,target){const type=unitTypes[attacker.type],base=roll(game,...type.damage),power=game.activePower,map=scenario(game),owner=game.units.find(u=>u.type===map.powerOwnerType&&alive(u));let modifier=0;if(owner&&power?.kind==='enhance'&&attacker.team===owner.team&&distance(owner,attacker)<=map.powers.enhance.range)modifier+=map.powers.enhance.bonus;if(owner&&power?.kind==='weaken'&&attacker.team!==owner.team&&distance(owner,attacker)<=map.powers.weaken.range)modifier-=map.powers.weaken.penalty;if(attacker.type==='luna'&&living(game,attacker.team).some(u=>u.type==='rekham'))modifier+=2;const damage=Math.max(0,base+modifier);target.hp=Math.max(0,target.hp-damage);log(game,`${unitTypes[attacker.type].name} hits ${unitTypes[target.type].name} for ${damage}.`);outcome(game);return damage;}
export function attack(game,targetId,attackerId=game.selectedId){const a=game.units.find(u=>u.id===attackerId&&alive(u)),t=game.units.find(u=>u.id===targetId&&alive(u));const type=a&&unitTypes[a.type],range=type?.range??1;if(!a||!t||game.result||game.turn!==a.team||a.team===t.team||a.acted||a.charmedRound===game.round||a.stunnedRound===game.round||t.invisible||distance(a,t)<1||distance(a,t)>range||(a.mp<(type.attackCost??0)))return false;
  if(a.type===scenario(game).powerOwnerType){if(!t.charmable){log(game,`${unitTypes[t.type].name} resists the charm.`);return false;}game.moveHistory=[];a.acted=true;game.activePower={kind:'charm',targetId:t.id};t.charmedRound=game.round;if(!game.charmedIds.includes(t.id)){game.charmedIds.push(t.id);if(scenario(game).allowRecruitment!==false){const reward=unitTypes[t.type].charmReward;game.charmPoints+=reward;log(game,`${unitTypes[a.type].name} charms ${unitTypes[t.type].name} and gains ${reward} charm point${reward===1?'':'s'}.`);}else log(game,`${unitTypes[a.type].name} charms ${unitTypes[t.type].name}.`);}else log(game,`${unitTypes[a.type].name} charms ${unitTypes[t.type].name}.`);outcome(game);return true;}
  game.moveHistory=[];a.acted=true;a.mp-=type.attackCost??0;const surprise=a.type==='luna'&&a.invisible;if(surprise){a.invisible=false;t.stunnedRound=game.round;}hit(game,a,t);if(surprise&&alive(t))log(game,`${unitTypes[t.type].name} is stunned for this turn.`);return true;}
export function turnInvisible(game,id=game.selectedId){const unit=game.units.find(u=>u.id===id&&alive(u));if(!unit||unit.type!=='luna'||game.turn!=='player'||game.result||unit.acted||unit.invisible)return false;game.moveHistory=[];unit.invisible=true;unit.acted=true;log(game,'Luna vanishes from sight.');return true;}
export function castPower(game,kind){const owner=game.units.find(u=>u.type===scenario(game).powerOwnerType&&alive(u));const power=scenario(game).powers[kind];if(!owner||!power||kind==='charm'||game.turn!==owner.team||game.result||owner.acted||owner.mp<power.cost)return false;game.moveHistory=[];owner.mp-=power.cost;owner.acted=true;game.activePower={kind};log(game,`${unitTypes[owner.type].name} casts ${power.name}.`);return true;}
export function endTurn(game){if(game.turn!=='player'||game.result||scenario(game).objective.kind==='hub')return false;game.moveHistory=[];game.turn='enemy';log(game,'The opposing army advances.');return true;}
function pathTo(game,unit,target){const map=scenario(game),queue=[[unit.x,unit.y]],parents=new Map([[key(unit.x,unit.y),null]]),blocked=new Set(living(game).filter(u=>u.id!==unit.id).map(u=>key(u.x,u.y)));let goal=null;for(let i=0;i<queue.length;i++){const [x,y]=queue[i],here=key(x,y);if(Math.abs(x-target.x)+Math.abs(y-target.y)<= (unitTypes[unit.type].range??1)){goal=here;break;}for(const [dx,dy] of DIRECTIONS){const nx=x+dx,ny=y+dy,next=key(nx,ny);if(nx<0||ny<0||nx>=map.width||ny>=map.height||game.terrain[ny][nx]==='tree'||blocked.has(next)||parents.has(next))continue;parents.set(next,here);queue.push([nx,ny]);}}if(!goal)return null;const route=[];for(let at=goal;parents.get(at)!==null;at=parents.get(at))route.unshift(at.split(',').map(Number));return route;}
function moveToward(game,unit,target){const path=pathTo(game,unit,target);if(!path)return false;const step=path[Math.min(path.length,unit.movesLeft)-1];return step?moveUnit(game,step[0],step[1],unit.id):false;}
function enemyStep(game,enemy){const preferred=scenario(game).ai.preferTargetType,visible=()=>living(game,'player').filter(u=>!u.invisible),nearby=()=>visible().filter(u=>distance(enemy,u)<= (unitTypes[enemy.type].range??1)).sort((a,b)=>(b.type===preferred)-(a.type===preferred)||a.hp-b.hp);if(nearby().length){attack(game,nearby()[0].id,enemy.id);return;}const targets=visible().sort((a,b)=>(b.type===preferred)-(a.type===preferred)||distance(enemy,a)-distance(enemy,b));for(const target of targets){const path=pathTo(game,enemy,target);if(!path)continue;const step=path[Math.min(path.length,enemy.movesLeft)-1];if(step)moveUnit(game,step[0],step[1],enemy.id);break;}const adjacent=nearby();if(adjacent.length)attack(game,adjacent[0].id,enemy.id);}
function charmedStep(game,enemy){const target=living(game,'enemy').filter(u=>!u.charmable&&u.id!==enemy.id&&distance(enemy,u)<= (unitTypes[enemy.type].range??1)).sort((a,b)=>a.hp-b.hp)[0];if(!target){log(game,'A charmed human is dazed.');return;}hit(game,enemy,target);if(alive(target)){target.retaliateAgainst=enemy.id;target.retaliateRound=game.round+1;log(game,`${unitTypes[target.type].name} vows to retaliate next turn.`);}}
function retaliationStep(game,enemy){if(enemy.retaliateRound!==game.round)return false;const target=game.units.find(u=>u.id===enemy.retaliateAgainst&&alive(u));enemy.retaliateAgainst=null;enemy.retaliateRound=0;if(!target)return false;if(distance(enemy,target)>1)moveToward(game,enemy,target);if(distance(enemy,target)===1){hit(game,enemy,target);log(game,`${unitTypes[enemy.type].name} retaliates against the former thrall.`);}else log(game,`${unitTypes[enemy.type].name} cannot reach its retaliation target.`);return true;}
export function finishEnemyTurn(game){if(game.turn!=='enemy'||game.result)return false;for(const enemy of living(game,'enemy')){if(!alive(enemy))continue;if(enemy.stunnedRound===game.round)log(game,`${unitTypes[enemy.type].name} is stunned and loses a turn.`);else if(enemy.charmedRound===game.round)charmedStep(game,enemy);else if(!retaliationStep(game,enemy))enemyStep(game,enemy);if(game.result)break;}if(game.activePower?.kind==='charm')game.activePower=null;if(!game.result){game.turn='player';game.round++;for(const unit of living(game)){unit.movesLeft=unitTypes[unit.type].move;unit.acted=false;}const current=selected(game);if(!current||current.team!=='player')game.selectedId=living(game,'player').find(u=>u.controllable!==false)?.id;log(game,`Round ${game.round} begins.`);}return true;}
export function exchangeCharmPoint(game){if(!game.result||scenario(game).allowRecruitment===false||game.result==='captured'||game.charmPoints<1)return false;game.charmPoints--;game.freshGoblins++;log(game,'One charm point is exchanged for a fresh goblin.');return true;}
export function nextBattle(game){const current=scenario(game),next=game.result==='victory'?current.nextScenario:current.onResult?.[game.result];if(!next)return null;const battle=createGame(game.seed,next);if(game.result==='captured')return battle;const map=scenario(battle),survivors=living(game,'player').filter(u=>u.type!=='broodmother');const additions=[...survivors.map(u=>({id:u.id,type:'veteran'})),...Array.from({length:game.freshGoblins},(_,i)=>({id:`recruit-${i+1}`,type:'goblin'}))];if(additions.length>map.partyDeployment.length)throw Error('Scenario needs more party deployment spaces');for(let i=0;i<additions.length;i++){const spec=additions[i],type=unitTypes[spec.type],{x,y}=map.partyDeployment[i];battle.terrain[y][x]='plain';battle.units.push({...spec,x,y,team:'player',hp:type.maxHp,mp:type.maxMp,movesLeft:type.move,acted:false,charmable:false,charmedRound:0,stunnedRound:0,invisible:false,retaliateAgainst:null,retaliateRound:0});}battle.charmPoints=game.charmPoints;battle.charmedIds=[...game.charmedIds];return battle;}
export function startMission(game,id){const board=scenario(game).missionBoard;if(!board?.includes(id)||game.result)return null;const mission=createGame(game.seed,id);mission.completedMissions=[...(game.completedMissions??[])];return mission;}
export function returnToGuild(game){const map=scenario(game);if(map.objective.kind==='hub'||map.allowRecruitment!==false||!game.result)return null;const hub=createGame(game.seed,'city-hub');hub.introPending=false;hub.completedMissions=[...(game.completedMissions??[])];if(game.result==='victory'&&!hub.completedMissions.includes(game.scenarioId))hub.completedMissions.push(game.scenarioId);return hub;}
export function upgradeCharmRewards(game){if(game.charmRewardVersion===2)return false;const definitions=Object.values(scenarios).flatMap(map=>map.units);for(const id of new Set(game.charmedIds)){const unit=game.units.find(u=>u.id===id)??definitions.find(u=>u.id===id);if(unit)game.charmPoints+=Math.max(0,unitTypes[unit.type].charmReward-1);}game.charmRewardVersion=2;return true;}
export function upgradeLegacyCapture(game){if(game.scenarioId!=='greenwood'||game.result!=='defeat'||game.units.find(u=>u.type==='broodmother')?.hp!==0)return false;game.result='captured';return true;}
export function validGame(game){const map=scenarios[game?.scenarioId];return !!(map&&game.version===3&&game.terrain?.length===map.height&&game.terrain.every(row=>row.length===map.width&&row.every(t=>t==='plain'||t==='tree'))&&Array.isArray(game.units)&&game.units.every(u=>unitTypes[u.type]&&Number.isInteger(u.x)&&Number.isInteger(u.y)&&u.x>=0&&u.y>=0&&u.x<map.width&&u.y<map.height&&Number.isInteger(u.hp)&&u.hp>=0&&u.hp<=unitTypes[u.type].maxHp&&typeof u.charmable==='boolean')&&['player','enemy'].includes(game.turn)&&Number.isInteger(game.round)&&Number.isInteger(game.charmPoints)&&game.charmPoints>=0&&Array.isArray(game.charmedIds)&&Number.isInteger(game.freshGoblins));}
