import {TILE,createGame,reachable,moveUnit,selectUnit,attack,castPower,endTurn,finishEnemyTurn,exchangeCharmPoint,validGame,living,selected,scenario} from './game.js';
import {unitTypes} from './scenarios.js';
const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
let game=createGame(),zoom=1,camera={x:0,y:0},dragging=false,dragStart,pointerStart,moved=false,follow=true,enemyTimer;
const ui={turn:$('#turnName'),round:$('#roundLabel'),name:$('#unitName'),role:$('#unitRole'),health:$('#health'),mana:$('#mana'),movement:$('#movement'),action:$('#action'),hint:$('#hint'),end:$('#endTurn'),toast:$('#toast'),party:$('#party'),powers:$('#powers'),log:$('#log'),result:$('#result')};
const dpr=()=>window.devicePixelRatio||1,bounds=()=>scenario(game);
function clamp(){camera.x=Math.max(0,Math.min(bounds().width*TILE-canvas.clientWidth/zoom,camera.x));camera.y=Math.max(0,Math.min(bounds().height*TILE-canvas.clientHeight/zoom,camera.y))}
function center(){const u=selected(game)||living(game,'player')[0]||living(game)[0];if(!u)return;camera.x=u.x*TILE+32-canvas.clientWidth/(2*zoom);camera.y=u.y*TILE+32-canvas.clientHeight/(2*zoom);clamp()}
function resize(){canvas.width=Math.round(canvas.clientWidth*dpr());canvas.height=Math.round(canvas.clientHeight*dpr());if(follow)center();draw()}
function noise(x,y,n=0){const v=Math.sin(x*127.1+y*311.7+n*83.2)*43758.5453;return v-Math.floor(v)}
function tile(x,y,type){const px=x*TILE,py=y*TILE;ctx.fillStyle=type==='tree'?'#426548':noise(x,y)>.5?'#76995b':'#709156';ctx.fillRect(px,py,TILE,TILE);ctx.fillStyle='#6b8e52';for(let i=0;i<6;i++)ctx.fillRect(px+noise(x,y,i)*56+4,py+noise(x+17,y,i)*55+5,2,5);if(type==='tree'){ctx.fillStyle='#324b36';ctx.beginPath();ctx.ellipse(px+33,py+51,22,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#705b3d';ctx.fillRect(px+28,py+31,9,24);for(const [ox,oy,r,c] of [[16,29,16,'#335c3c'],[44,28,16,'#2e573b'],[31,18,22,'#3e6a43'],[26,17,13,'#56804c']]){ctx.fillStyle=c;ctx.beginPath();ctx.arc(px+ox,py+oy,r,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='#203b2b1c';ctx.strokeRect(px+.5,py+.5,TILE,TILE)}
function drawUnit(u){const x=u.x*TILE+32,y=u.y*TILE+32,mother=u.type==='broodmother',enemy=u.team==='enemy';ctx.fillStyle='#16281988';ctx.beginPath();ctx.ellipse(x,y+21,19,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=enemy?'#e8a17d':mother?'#d8b5e6':'#b9e277';ctx.beginPath();ctx.arc(x,y,21,0,Math.PI*2);ctx.fill();ctx.fillStyle=enemy?'#bfc3b8':mother?'#694678':'#335e31';ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.fill();if(!enemy){ctx.fillStyle=mother?'#a478aa':'#86b85a';ctx.beginPath();ctx.moveTo(x-15,y-6);ctx.lineTo(x-24,y-17);ctx.lineTo(x-8,y-15);ctx.moveTo(x+15,y-6);ctx.lineTo(x+24,y-17);ctx.lineTo(x+8,y-15);ctx.fill();ctx.fillStyle='#f2e5ab';ctx.fillRect(x-8,y-3,5,4);ctx.fillRect(x+4,y-3,5,4)}else{ctx.fillStyle='#414c4c';ctx.fillRect(x-14,y-15,28,8);ctx.fillStyle='#ead8c0';ctx.fillRect(x-10,y-4,20,10);ctx.fillStyle='#493a35';ctx.fillRect(x-7,y,4,3);ctx.fillRect(x+4,y,4,3)}ctx.strokeStyle=u.id===game.selectedId?'#fff3b5':enemy?'#ffd1b5':'#d7f1ae';ctx.lineWidth=u.id===game.selectedId?4:2;ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.stroke();if(enemy&&u.charmable){ctx.fillStyle='#72c9ff';ctx.strokeStyle='#d5f2ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+17,y-17,7,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.fillStyle='#1a281d';ctx.fillRect(x-21,y+27,42,6);ctx.fillStyle=enemy?'#e59b83':'#b9dd7f';ctx.fillRect(x-20,y+28,40*u.hp/unitTypes[u.type].maxHp,4);if(u.charmedRound===game.round){ctx.fillStyle='#f5b6f5';ctx.font='bold 20px sans-serif';ctx.fillText('♥',x+13,y-18)}}
function draw(){ctx.setTransform(dpr(),0,0,dpr(),0,0);ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.fillStyle='#1c3427';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.translate(-camera.x*zoom,-camera.y*zoom);ctx.scale(zoom,zoom);const left=Math.max(0,Math.floor(camera.x/TILE)),top=Math.max(0,Math.floor(camera.y/TILE)),right=Math.min(bounds().width,Math.ceil((camera.x+canvas.clientWidth/zoom)/TILE)),bottom=Math.min(bounds().height,Math.ceil((camera.y+canvas.clientHeight/zoom)/TILE));for(let y=top;y<bottom;y++)for(let x=left;x<right;x++)tile(x,y,game.terrain[y][x]);const u=selected(game);if(game.turn==='player'&&!game.result&&u?.team==='player'){ctx.fillStyle='#a6dffb55';ctx.strokeStyle='#bceaff99';ctx.lineWidth=1;for(const [position,cost] of reachable(game,u)){if(!cost)continue;const [x,y]=position.split(',').map(Number);ctx.fillRect(x*TILE+2,y*TILE+2,TILE-4,TILE-4);ctx.strokeRect(x*TILE+2.5,y*TILE+2.5,TILE-5,TILE-5)}}for(const unit of living(game))drawUnit(unit)}
function toast(message){ui.toast.textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>ui.toast.textContent='',3500)}
function update(){const map=scenario(game),u=selected(game),type=u&&unitTypes[u.type];$('#scenarioName').textContent=map.name;$('#scenarioDescription').textContent=map.description;$('#mapName').textContent=map.name.toUpperCase();$('#mapSize').textContent=`${map.width} × ${map.height}`;$('#charmPoints').textContent=game.charmPoints;ui.turn.textContent=game.result?'Battle over':game.turn==='player'?'Player turn':'Human turn';ui.round.textContent=`Round ${game.round}`;ui.name.textContent=u?`${type.name}${u.type==='goblin'?' '+u.id.split('-')[1]:''}`:'No unit';ui.role.textContent=u?(u.team==='player'?'Your party':u.charmable?'Human army · Charmable':'Human army · Resolute'):'—';ui.health.textContent=u?`${u.hp} / ${type.maxHp}`:'—';ui.mana.textContent=u?`${u.mp} / ${type.maxMp}`:'—';ui.movement.textContent=u?`${u.movesLeft} / ${type.move}`:'—';ui.action.textContent=u?(u.acted?'Used':'Ready'):'—';ui.hint.textContent=game.result?({victory:'The humans are defeated. Your party wins!',defeat:'The broodmother has fallen.','last-mother':'Only the broodmother remains alive.'})[game.result]:game.turn==='enemy'?'The humans are taking their turn…':u?.team==='enemy'?'Select one of your goblins.':'Click a blue square to move, or an adjacent human to attack.';ui.end.disabled=!!game.result||game.turn!=='player';ui.party.replaceChildren(...game.units.filter(a=>a.team==='player').map(a=>{const b=document.createElement('button');b.className=`party-unit${a.id===game.selectedId?' active':''}${a.hp<=0?' dead':''}`;b.textContent=`${a.type==='broodmother'?'♛':'♟'} ${a.type==='broodmother'?'Broodmother':'Goblin '+a.id.split('-')[1]} · ${a.hp}/${unitTypes[a.type].maxHp}`;b.disabled=a.hp<=0;b.onclick=()=>{selectUnit(game,a.id);follow=true;center();update()};return b}));ui.powers.hidden=u?.type!==map.powerOwnerType;for(const kind of ['enhance','weaken']){const b=$(`#${kind}`);b.disabled=game.turn!=='player'||!!game.result||u?.type!==map.powerOwnerType||u.acted||u.mp<map.powers[kind].cost;b.classList.toggle('active',game.activePower?.kind===kind)}$('#charmStatus').textContent=game.activePower?.kind==='charm'?'Charm active until the human turn ends':game.activePower?.kind==='enhance'?'Battle chant active (+2 ally damage in 3 tiles)':game.activePower?.kind==='weaken'?'Withering curse active (−2 human damage in 3 tiles)':'No power active';ui.log.replaceChildren(...game.log.slice(0,4).map(message=>{const p=document.createElement('p');p.textContent=message;return p}));ui.result.hidden=!game.result;ui.result.textContent=game.result?`${ui.hint.textContent} ${game.charmPoints} charm point${game.charmPoints===1?'':'s'} available.`:'';$('#rewards').hidden=!game.result;$('#freshGoblins').textContent=game.freshGoblins;$('#exchangeCharm').disabled=!game.result||game.charmPoints<1;draw()}
function at(x,y){return living(game).find(u=>u.x===x&&u.y===y)}
function interact(x,y){const target=at(x,y),u=selected(game);if(target){if(target.team==='player'){selectUnit(game,target.id);follow=true;center();update()}else if(u?.team==='player'){if(attack(game,target.id)){update();toast(game.log[0])}else if(u.type===scenario(game).powerOwnerType&&!target.charmable)toast('This human cannot be charmed. Blue-marked humans can.');else toast('Move adjacent to attack with an unused action.')}return}if(moveUnit(game,x,y)){follow=true;center();update()}else if(game.turn==='player'&&!game.result)toast('That square is out of reach.')}
canvas.addEventListener('pointerdown',e=>{dragging=true;moved=false;dragStart={x:e.clientX,y:e.clientY};pointerStart={...camera};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved){follow=false;camera.x=pointerStart.x-dx/zoom;camera.y=pointerStart.y-dy/zoom;clamp();draw()}});
canvas.addEventListener('pointerup',e=>{dragging=false;if(moved)return;const rect=canvas.getBoundingClientRect(),x=Math.floor((camera.x+(e.clientX-rect.left)/zoom)/TILE),y=Math.floor((camera.y+(e.clientY-rect.top)/zoom)/TILE);interact(x,y)});
canvas.addEventListener('wheel',e=>{e.preventDefault();const old=zoom;zoom=Math.max(.7,Math.min(1.6,zoom+(e.deltaY<0?.1:-.1)));const rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top;camera.x+=px/old-px/zoom;camera.y+=py/old-py/zoom;clamp();draw()},{passive:false});
window.addEventListener('keydown',e=>{const d={ArrowUp:[0,-1],KeyW:[0,-1],ArrowDown:[0,1],KeyS:[0,1],ArrowLeft:[-1,0],KeyA:[-1,0],ArrowRight:[1,0],KeyD:[1,0]}[e.code];if(d){e.preventDefault();const u=selected(game);if(u)interact(u.x+d[0],u.y+d[1])}});
ui.end.onclick=()=>{if(!endTurn(game))return;update();enemyTimer=setTimeout(()=>{finishEnemyTurn(game);update();toast(game.log[0])},550)};
for(const kind of ['enhance','weaken'])$(`#${kind}`).onclick=()=>{if(castPower(game,kind)){update();toast(game.log[0])}};
$('#newGame').onclick=()=>{clearTimeout(enemyTimer);game=createGame(Math.floor(Math.random()*1e9));follow=true;center();update();toast('A new battle is ready.')};
$('#saveGame').onclick=()=>{localStorage.setItem('battlemap-save-v3',JSON.stringify(game));toast('Battle saved in this browser.')};
$('#loadGame').onclick=()=>{try{const loaded=JSON.parse(localStorage.getItem('battlemap-save-v3'));if(!validGame(loaded))throw Error('Invalid save');clearTimeout(enemyTimer);game=loaded;if(game.turn==='enemy'&&!game.result)finishEnemyTurn(game);follow=true;center();update();toast('Battle loaded.')}catch{toast('No valid saved battle found.')}};
$('#exchangeCharm').onclick=()=>{if(exchangeCharmPoint(game)){update();toast('A fresh goblin joins the brood.')}};
new ResizeObserver(resize).observe(canvas);update();
